"""returning to old user

Revision ID: 1ea9f1f9d283
Revises: 4aa5d65e198a
Create Date: 2025-04-07 17:49:18.561412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea9f1f9d283'
down_revision: Union[str, None] = '4aa5d65e198a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'username', sa.String(length=100)))
    op.create_index(op.f('ix_users_username'),
                    'users', ['username'], unique=True)
    op.drop_column('users', 'avatar_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_path', sa.VARCHAR(
        length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
