"""Initial migration

Revision ID: 36836f2d44ef
Revises: 
Create Date: 2025-04-03 17:46:46.172234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36836f2d44ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credits',
    sa.Column('credit_id', sa.String(length=100), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('credit_id'),
    sa.UniqueConstraint('content_id', 'content_type', name='_content_uc')
    )
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_table('movies',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('backdrop_path', sa.String(length=255), nullable=True),
    sa.Column('adult', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('tmdb_id')
    )
    op.create_table('persons',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('profile_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('tv_shows',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('first_air_date', sa.Date(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('backdrop_path', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('tmdb_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cast_members',
    sa.Column('credit_id', sa.String(length=100), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.credit_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.person_id'], ),
    sa.PrimaryKeyConstraint('credit_id')
    )
    op.create_table('movie_genres',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.genre_id'], ),
    sa.ForeignKeyConstraint(['tmdb_id'], ['movies.tmdb_id'], ),
    sa.PrimaryKeyConstraint('tmdb_id', 'genre_id')
    )
    op.create_table('tv_genres',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.genre_id'], ),
    sa.ForeignKeyConstraint(['tmdb_id'], ['tv_shows.tmdb_id'], ),
    sa.PrimaryKeyConstraint('tmdb_id', 'genre_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('tv_genres')
    op.drop_table('movie_genres')
    op.drop_table('cast_members')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tv_shows')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('persons')
    op.drop_table('movies')
    op.drop_table('genres')
    op.drop_table('credits')
    # ### end Alembic commands ###
