"""final migration before PR

Revision ID: 580495cebab3
Revises: 8b58e8f32455
Create Date: 2025-04-06 22:34:25.884415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '580495cebab3'
down_revision: Union[str, None] = '8b58e8f32455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_credits')
    op.drop_table('tv_credits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tv_credits',
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credit_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.credit_id'], name='tv_credits_credit_id_fkey'),
    sa.ForeignKeyConstraint(['tmdb_id'], ['tv_shows.tmdb_id'], name='tv_credits_tmdb_id_fkey'),
    sa.PrimaryKeyConstraint('tmdb_id', 'credit_id', name='tv_credits_pkey')
    )
    op.create_table('movie_credits',
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credit_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.credit_id'], name='movie_credits_credit_id_fkey'),
    sa.ForeignKeyConstraint(['tmdb_id'], ['movies.tmdb_id'], name='movie_credits_tmdb_id_fkey'),
    sa.PrimaryKeyConstraint('tmdb_id', 'credit_id', name='movie_credits_pkey')
    )
    # ### end Alembic commands ###
