"""creating separate credits pages

Revision ID: 8b58e8f32455
Revises: 9f1411b23a4b
Create Date: 2025-04-06 22:23:24.575446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b58e8f32455'
down_revision: Union[str, None] = '9f1411b23a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_credits',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.credit_id'], ),
    sa.ForeignKeyConstraint(['tmdb_id'], ['movies.tmdb_id'], ),
    sa.PrimaryKeyConstraint('tmdb_id', 'credit_id')
    )
    op.create_table('tv_credits',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.credit_id'], ),
    sa.ForeignKeyConstraint(['tmdb_id'], ['tv_shows.tmdb_id'], ),
    sa.PrimaryKeyConstraint('tmdb_id', 'credit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tv_credits')
    op.drop_table('movie_credits')
    # ### end Alembic commands ###
