"""fixing persons

Revision ID: cc48721543cd
Revises: 1affebef1870
Create Date: 2025-04-05 12:30:10.801398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc48721543cd'
down_revision: Union[str, None] = '1affebef1870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_content_uc', 'credits', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_content_uc', 'credits', ['content_id', 'content_type'])
    # ### end Alembic commands ###
