"""creadting connecting tables for credits and content

Revision ID: cc86eff3bce7
Revises: 51c9f23e56d2
Create Date: 2025-04-07 13:18:47.548889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc86eff3bce7'
down_revision: Union[str, None] = '51c9f23e56d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_credits',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.credit_id'], ),
    sa.ForeignKeyConstraint(['tmdb_id'], ['movies.tmdb_id'], ),
    sa.PrimaryKeyConstraint('tmdb_id', 'credit_id')
    )
    op.create_table('tv_credits',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.credit_id'], ),
    sa.ForeignKeyConstraint(['tmdb_id'], ['tv_shows.tmdb_id'], ),
    sa.PrimaryKeyConstraint('tmdb_id', 'credit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tv_credits')
    op.drop_table('movie_credits')
    # ### end Alembic commands ###
