"""test  migration

Revision ID: f0a426f53e9a
Revises: 36836f2d44ef
Create Date: 2025-04-03 22:19:32.192527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a426f53e9a'
down_revision: Union[str, None] = '36836f2d44ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crew_members',
    sa.Column('credit_id', sa.String(length=100), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('job', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.credit_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.person_id'], ),
    sa.PrimaryKeyConstraint('credit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crew_members')
    # ### end Alembic commands ###
