"""removing credits

Revision ID: fb0b7b2b5a5d
Revises: cc86eff3bce7
Create Date: 2025-04-07 17:18:05.117098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0b7b2b5a5d'
down_revision: Union[str, None] = 'cc86eff3bce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_credits')
    op.drop_table('tv_credits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tv_credits',
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credit_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.credit_id'], name='tv_credits_credit_id_fkey'),
    sa.ForeignKeyConstraint(['tmdb_id'], ['tv_shows.tmdb_id'], name='tv_credits_tmdb_id_fkey'),
    sa.PrimaryKeyConstraint('tmdb_id', 'credit_id', name='tv_credits_pkey')
    )
    op.create_table('movie_credits',
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credit_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.credit_id'], name='movie_credits_credit_id_fkey'),
    sa.ForeignKeyConstraint(['tmdb_id'], ['movies.tmdb_id'], name='movie_credits_tmdb_id_fkey'),
    sa.PrimaryKeyConstraint('tmdb_id', 'credit_id', name='movie_credits_pkey')
    )
    # ### end Alembic commands ###
